[[services]]
name = "lingo-challenge-backend"
source = "backend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "lingo-challenge-frontend"
source = "."

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
