[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start:bun"
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "lingo-challenge-backend"
source = "backend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[services.deploy]
startCommand = "bun run src/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "lingo-challenge-frontend"
source = "."

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "bun run dev"
healthcheckPath = "/"
healthcheckTimeout = 300
