services:
  - type: web
    name: lingo-challenge
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildCommand: npm run build
    startCommand: npm run backend:dev:npm
